DistantLearning/Models/Question.cs
namespace DistantLearning.Models
{
    public class Question
    {
        public int QuestionId { get; set; }
        public string? QuestionName { get; set; }
        public string? QuestionAnswer { get; set; }
        public int TestId { get; set; }
        public virtual Test? Test { get; set; } 

    }
}

DistantLearning/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DistantLearning.Models;
using Microsoft.AspNetCore.Authorization;

namespace DistantLearning.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class QuestionsController : Controller
    {
        private readonly DBcontext _context;

        public QuestionsController(DBcontext context)
        {
            _context = context;
        }

        // GET: Questions
        public async Task<IActionResult> Index()
        {
            var dBcontext = _context.questions.Include(q => q.Test);
            return View(await dBcontext.ToListAsync());
        }

        // GET: Questions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.questions
                .Include(q => q.Test)
                .FirstOrDefaultAsync(m => m.QuestionId == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // GET: Questions/Create
        public IActionResult Create()
        {
            ViewData["TestId"] = new SelectList(_context.tests, "TestId", "TestId");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( int id, [Bind("QuestionId,QuestionName,QuestionAnswer,TestId")] Question question)
        {
            question.TestId = id;
            if (ModelState.IsValid)
            {
                _context.Add(question);
                await _context.SaveChangesAsync();
                return Redirect("~/Tests");
            }
            return View(question);
        }

        // GET: Questions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.questions.FindAsync(id);
            if (question == null)
            {
                return NotFound();
            }
            ViewData["TestId"] = new SelectList(_context.tests, "TestId", "TestId", question.TestId);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("QuestionId,QuestionName,QuestionAnswer,TestId")] Question question)
        {
            if (id != question.QuestionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.QuestionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TestId"] = new SelectList(_context.tests, "TestId", "TestId", question.TestId);
            return View(question);
        }

        // GET: Questions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.questions
                .Include(q => q.Test)
                .FirstOrDefaultAsync(m => m.QuestionId == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var question = await _context.questions.FindAsync(id);
            _context.questions.Remove(question);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuestionExists(int id)
        {
            return _context.questions.Any(e => e.QuestionId == id);
        }
    }
}

DistantLearning/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DistantLearning.Models;
using Microsoft.AspNetCore.Authorization;

namespace DistantLearning.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class TestsController : Controller
    {
        private readonly DBcontext _context;

        public TestsController(DBcontext context)
        {
            _context = context;
        }

        // GET: Tests
        public async Task<IActionResult> Index()
        {
            var dBcontext = _context.tests.Include(t => t.Subject);
            return View(await dBcontext.ToListAsync());
        }

        // GET: Tests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.tests
                .Include(t => t.Subject)
                .FirstOrDefaultAsync(m => m.TestId == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // GET: Tests/Create
        public IActionResult Create()
        {
            ViewData["SubjectId"] = new SelectList(_context.subjects, "SubjectId", "SubjectName");
            return View();
        }

        // POST: Tests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TestId,TestName,SubjectId")] Test test)
        {
            if (ModelState.IsValid)
            {
                _context.Add(test);
                await _context.SaveChangesAsync(); 
                Question QuestionTest = new Question();
                QuestionTest.TestId = test.TestId;
                QuestionTest.QuestionName = "hiddenanswer";
                QuestionTest.QuestionAnswer = "hiddenanswer";
                _context.questions.Add(QuestionTest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.subjects, "SubjectId", "SubjectId", test.SubjectId);
            return View(test);
        }




        // GET: Tests/Edit/5
        public async Task<IActionResult> Edit(int? id, [Bind("QuestionId,QuestionName,QuestionAnswer,TestId")] Question question)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.tests.FindAsync(id);
            if (test == null)
            {
                return NotFound();
            }
            var dBcontext = _context.questions.Where(c => c.TestId == id);
            return View(await dBcontext.ToListAsync());
        }

        // POST: Tests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TestId,TestName,SubjectId")] Test test)
        {
            if (id != test.TestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(test);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestExists(test.TestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.subjects, "SubjectId", "SubjectId", test.SubjectId);
            return View(test);
        }

        // GET: Tests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.tests
                .Include(t => t.Subject)
                .FirstOrDefaultAsync(m => m.TestId == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        // POST: Tests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            foreach (var answercomp in _context.questions)
            {
                if (answercomp.TestId == id)
                {
                    _context.questions.Remove(answercomp);
                }
            }
            var test = await _context.tests.FindAsync(id);
            _context.tests.Remove(test);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestExists(int id)
        {
            return _context.tests.Any(e => e.TestId == id);
        }
    }
}

DistantLearning/Views/Questions/Create.cshtml
@model DistantLearning.Models.Question

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="QuestionName" class="control-label"></label>
                <input asp-for="QuestionName" class="form-control" />
                <span asp-validation-for="QuestionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuestionAnswer" class="control-label"></label>
                <input asp-for="QuestionAnswer" class="form-control" />
                <span asp-validation-for="QuestionAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
  @Html.ActionLink("Обратно","Index","Tests")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DistantLearning/Views/Questions/Delete.cshtml
@model DistantLearning.Models.Question

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuestionName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuestionAnswer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Test)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Test.TestId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="QuestionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DistantLearning/Views/Questions/Details.cshtml
@model DistantLearning.Models.Question

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuestionName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuestionAnswer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Test)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Test.TestId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.QuestionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DistantLearning/Views/Questions/Edit.cshtml
@model DistantLearning.Models.Question

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="QuestionId" />
            <div class="form-group">
                <label asp-for="QuestionName" class="control-label"></label>
                <input asp-for="QuestionName" class="form-control" />
                <span asp-validation-for="QuestionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuestionAnswer" class="control-label"></label>
                <input asp-for="QuestionAnswer" class="form-control" />
                <span asp-validation-for="QuestionAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TestId" class="control-label"></label>
                <select asp-for="TestId" class="form-control" asp-items="ViewBag.TestId"></select>
                <span asp-validation-for="TestId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DistantLearning/Views/Questions/Index.cshtml
@model IEnumerable<DistantLearning.Models.Question>

@{
    ViewData["Title"] = "Index";
}

<h1>Вопросы</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.QuestionName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuestionAnswer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Test)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionAnswer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Test.TestId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.QuestionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.QuestionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.QuestionId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>